# nix run nixpkgs#ssh-to-age -- -private-key -i .ssh/id_ed25519 > ~/.config/sops/age/keys.txt
# nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt

keys:
  - &hosts:
    - &le: age...
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *le
