# Created by Zap installer
if [ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ]; then
  zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 --keep
fi
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"


plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/options.zsh"
plug "$HOME/.config/zsh/keybindings.zsh"

#plug "zap-zsh/supercharge"
#plug "zap-zsh/zap-prompt"

# plug "zsh-users/zsh-syntax-highlighting"
# plug "zsh-users/zsh-autosuggestions"
# plug "zsh-users/zsh-completions"

# plug "zsh-users/zsh-history-substring-search"
# plug "Aloxaf/fzf-tab"
# plug "Freed-Wu/fzf-tab-source"

# Load and initialise completion system
autoload -Uz compinit
compinit

# eval "$(/opt/homebrew/bin/mise activate zsh)"
eval "$(starship init zsh)"
# shellcheck disable=SC1090
source <(fzf --zsh)
eval "$(zoxide init zsh)"
PATH="$HOME/.local/bin/:$PATH"

# shellcheck disable=SC1090
[[ ${commands[kubectl]} ]] && source <(kubectl completion zsh)

# AWS CLI completion for zsh
if [[ -x "$(command -v aws_completer)" ]]; then
  compdef _aws aws
  function _aws {
    local IFS=$'\n'
    compadd -- "$(aws_completer "$@")"
  }
  compdef _aws aws-vault
  compdef _aws sudo
fi

autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
complete -C 'aws_completer' aws

[[ ${commands[kubectl]} ]] && source <(kubectl completion zsh)
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
