name: CI 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Quick smoke tests that run first
  smoke-test:
    name: Smoke Test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Quick flake check
        run: nix flake check --no-build

      - name: Quick build test
        run: nix build .#darwinConfigurations.le.system --dry-run

  # Call other workflow jobs
  test:
    name: Run Tests
    needs: smoke-test
    uses: ./.github/workflows/test.yml

  quality:
    name: Code Quality
    needs: smoke-test
    uses: ./.github/workflows/quality.yml

  validation:
    name: Validation
    needs: smoke-test
    uses: ./.github/workflows/validation.yml

  # Summary job that depends on all others
  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [smoke-test, test, quality, validation]
    if: always()
    steps:
      - name: Check results
        run: |
          echo "CI Summary:"
          echo "==========="
          echo "Smoke Test: ${{ needs.smoke-test.result }}"
          echo "Tests: ${{ needs.test.result }}"
          echo "Quality: ${{ needs.quality.result }}"
          echo "Validation: ${{ needs.validation.result }}"
          
          # Determine overall status
          if [[ "${{ needs.smoke-test.result }}" == "success" && \
                "${{ needs.test.result }}" == "success" && \
                "${{ needs.quality.result }}" == "success" && \
                "${{ needs.validation.result }}" == "success" ]]; then
            echo "✅ All CI checks passed!"
            exit 0
          else
            echo "❌ Some CI checks failed!"
            exit 1
          fi