# Flake checker workflow for monitoring flake health and dependencies
name: Flake ❄️ Checker ✅

on:
  push:
    branches:
      - main
  schedule:
    # Run daily at 13:37 UTC (l33t o'clock)
    - cron: '37 13 * * *'
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake Health Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run Flake Checker
        uses: DeterminateSystems/flake-checker-action@v8
        with:
          # Check for outdated inputs and other flake health issues
          fail-mode: false

      - name: Check flake metadata
        run: |
          echo "Flake metadata:"
          nix flake metadata --json | jq '.'
          
          echo "Input status:"
          nix flake metadata --json | jq -r '.locks.nodes | to_entries[] | select(.value.locked) | "\(.key): \(.value.locked.lastModified // "unknown") (\(.value.locked.rev // .value.locked.ref // "unknown"))"'